---
- name: create symlinks
  become: true
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.USER }}"
    state: link
    force: true
  loop: "{{ scripts_symlinks }}"
