- name: change application style to kvantum dark
  become: true
  shell: >
    kwriteconfig5 --file "{{ user_home }}/.config/kdeglobals" --group KDE \
    --key widgetStyle kvantum-dark

- name: change gnome/gtk application style
  become_user: "{{ host_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: "{{ dbus_session_bus_address }}"
  shell: dbus-send --session --dest=org.kde.GtkConfig --type=method_call /GtkConfig org.kde.GtkConfig.setGtkTheme 'string:Layan-Dark-Solid'
