---
- name: check if cargo is installed
  become_user: "{{ ansible_env.USER }}"
  stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  register: cargo_path
  ignore_errors: true
  changed_when: false

- name: download rust installer
  become: true
  become_user: "{{ ansible_env.USER }}"
  when: not cargo_path.stat.exists
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "u+rwx"
    owner: "{{ ansible_env.USER }}"
    force: true

- name: install rust/cargo
  become: true
  become_user: "{{ ansible_env.USER }}"
  when: not cargo_path.stat.exists
  shell: /tmp/sh.rustup.rs -y

- name: remove rust installer
  file:
    path: "/tmp/sh.rustup.rs"
    state: absent

- name: install rust toolchain
  shell: rustup toolchain remove stable && rustup toolchain install stable
  changed_when: false
  args:
    executable: /bin/bash
