- name: get layan repository
  git:
    repo: "https://github.com/vinceliuice/Layan-kde.git"
    dest: "/tmp/Layan-kde"
    clone: yes
    update: yes

- name: get layan gtk theme repository
  git:
    repo: "https://github.com/vinceliuice/Layan-gtk-theme.git"
    dest: "/tmp/Layan-gtk-theme"
    clone: yes
    update: yes

- name: install layan kvantum theme and layan kde theme
  shell: |
    /tmp/Layan-kde/install.sh
    /tmp/Layan-gtk-theme/install.sh

- name: change kvantum theme to layan
  become_user: "{{ host_user }}"
  shell: >
    kwriteconfig5 --file "{{ user_home }}/.config/Kvantum/kvantum.kvconfig" \
      --group General \
      --key theme LayanSolidDark
