---
- name: install flatpak (linux)
  apt:
    name:
      - flatpak
    state: present
  when: is_debian_distro

- name: add flathub repository (linux)
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  when: is_debian_distro

- name: install discord (linux)
  flatpak:
    name: com.discordapp.Discord
    method: user
    users: "{{ host_user }}"
    state: present
  when: is_debian_distro and has_extra_software

- name: install firefox (linux)
  flatpak:
    name: org.mozilla.firefox
    method: user
    users: "{{ host_user }}"
    state: present
  when: is_debian_distro and has_extra_software

- name: install obsidian (linux)
  flatpak:
    name: md.obsidian.Obsidian
    method: user
    users: "{{ host_user }}"
    state: present
  when: is_debian_distro and has_extra_software

- name: install postman (linux)
  flatpak:
    name: com.getpostman.Postman
    method: user
    users: "{{ host_user }}"
    state: present
  when: is_debian_distro and has_extra_software

- name: install slack (linux)
  flatpak:
    name: com.slack.Slack
    method: user
    users: "{{ host_user }}"
    state: present
  when: is_debian_distro and has_extra_software

- name: install spotify (linux)
  flatpak:
    name: com.spotify.Client
    method: user
    users: "{{ host_user }}"
    state: present
  when: is_debian_distro and has_extra_software

- name: install obs (linux)
  flatpak:
    name: com.obsproject.Studio
    method: user
    users: "{{ host_user }}"
    state: present
  when: is_debian_distro and has_extra_software

- name: install bitwarden (linux)
  flatpak:
    name: com.bitwarden.desktop
    method: user
    users: "{{ host_user }}"
    state: present
  when: is_debian_distro and has_extra_software
...
