---
- name: install flatpak (linux)
  apt:
    name:
      - flatpak
    state: present
  when: is_debian_distro

- name: add flathub repository (linux)
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  when: is_debian_distro

- name: install flatpak packages (linux)
  become: true
  become_user: "{{ host_user }}"
  flatpak:
    name: "{{ item }}"
    method: user
    state: present
  when: is_debian_distro and has_extra_software
  loop:
    - com.brave.Browser
    - com.slack.Slack
    - com.spotify.Client
    - com.discordapp.Discord
    - md.obsidian.Obsidian
    - com.getpostman.Postman
    - com.obsproject.Studio
    - com.bitwarden.desktop
    - com.dropbox.Client
...
