---
galaxy_info:
  author: drew138
  description: installs homebrew casks
  license: MIT
  min_ansible_version: 2.16.1
  role_name: casks
  namespace: drew138
  platforms:
    - name: MacOSX
      versions:
        - all
dependencies:
  - role: homebrew
