---
- name: install kitty
  become: true
  become_user: "{{ host_user }}"
  ansible.builtin.shell: >
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  when: has_kitty_terminal

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ user_home }}/.local/bin/"
    - "{{ user_home }}/.local/share/"
    - "{{ user_home }}/.local/share/applications/"
    - "{{ user_home }}/.config/"
    - "{{ user_home }}/.config/kitty/"

- name: create symbolic link for kitty binary
  file:
    src: "{{ user_home }}/.local/kitty.app/bin/kitty"
    dest: "{{ user_home }}/.local/bin/kitty"
    owner: "{{ host_user }}"
    state: link
    force: true
  when: is_debian_distro

- name: copy kitty.desktop file
  copy:
    src: "{{ kitty_desktop_path }}"
    dest: "{{ user_home }}/.local/share/applications/"
  when: is_debian_distro

- name: copy kitty-open.desktop file
  copy:
    src: "{{ kitty_open_desktop_path }}"
    dest: "{{ user_home }}/.local/share/applications/"
  when: is_debian_distro

- name: update paths in kitty.desktop file(s)
  replace:
    path: "{{ item }}"
    regexp: "(Icon=)kitty"
    replace: "\\1{{ kitty_png_path }}"
  with_fileglob:
    - "{{ user_home }}/.local/share/applications/kitty*.desktop"
  when: is_debian_distro

- name: update paths in kitty.desktop file(s)
  replace:
    path: "{{ item }}"
    regexp: "(Exec=)kitty"
    replace: "\\1{{ user_home }}/.local/kitty.app/bin/kitty"
  with_fileglob:
    - "{{ user_home }}/.local/share/applications/kitty*.desktop"
  when: is_debian_distro

- name: create kitty.conf symlink
  file:
    src: "{{ user_home }}/.dotfiles/.config/kitty/kitty.conf"
    dest: "{{ user_home }}/.config/kitty/kitty.conf"
    owner: "{{ host_user }}"
    state: link
    force: true

- name: create nightfox_kitty.conf symlink
  file:
    src: "{{ user_home }}/.dotfiles/.config/kitty/nightfox_kitty.conf"
    dest: "{{ user_home }}/.config/kitty/nightfox_kitty.conf"
    owner: "{{ host_user }}"
    state: link
    force: true
