- name: get applet latte separator repository
  git:
    repo: "https://github.com/psifidotos/applet-latte-separator.git"
    dest: "/tmp/applet-latte-separator"
    clone: yes
    update: yes

- name: install latte separator
  become: true
  become_user: "{{ host_user }}"
  command: plasmapkg2 -i /tmp/applet-latte-separator
  args:
    creates: "{{ user_home }}/.local/share/plasma/plasmoids/org.kde.latte.separator"
