---
- name: check if nvm is installed
  become_user: "{{ ansible_env.USER }}"
  stat:
    path: "{{ ansible_env.HOME }}/.nvm"
  register: nvm_path
  ignore_errors: true
  changed_when: false

- name: get latest version of nvm
  shell: "basename $(curl -fs -o/dev/null -w %{redirect_url} https://github.com/nvm-sh/nvm/releases/latest)"
  register: nvm_latest_version
  changed_when: false

- name: check current nvm installation version
  become: true
  shell: "{{ ansible_env.HOME }}/.nvm/nvm.sh && nvm -v"
  register: nvm_output_version
  when: nvm_path.stat.exists

- name: set nvm version when nvm not installed
  set_fact:
    nvm_local_version: "{{ nvm_output_version.stdout }}"
  when: nvm_path.stat.exists

- name: set nvm version when nvm is not installed
  set_fact:
    nvm_local_version: ""
  when: not nvm_path.stat.exists

- name: Download script from URL
  get_url:
    url: "{{ nvm_script_url }}"
    dest: "/tmp/nvm_installer.sh"
    mode: "+x"
  when: nvm_local_version != nvm_latest_version.stdout

- name: install nvm
  become: true
  become_user: "{{ ansible_env.USER }}"
  shell: "/tmp/nvm_installer.sh" 
  # environment: {}
  when: nvm_local_version != nvm_latest_version.stdout

- name: Remove the script file
  file:
    path: "/tmp/nvm_installer.sh"
    state: absent
