---
- name: get latest version of nvm
  shell: "basename $(curl -fs -o/dev/null -w %{redirect_url} https://github.com/nvm-sh/nvm/releases/latest)"
  register: nvm_latest_version
  changed_when: false

- name: clone nvm repository
  become: true
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: "https://github.com/nvm-sh/nvm.git"
    dest: "{{ ansible_env.HOME }}/.nvm"
    version: "{{ nvm_latest_version.stdout }}"
    depth: 1
    clone: true
    force: true
