---
with-expecter: true
dir: installer/mocks
mockname: "{{.InterfaceName}}"
outpkg: mocks
filename: "{{.InterfaceName}}.go"
all: true
packages:
  github.com/drew138/.dotfiles/installer/internal/application:
    config:
      all: true
  github.com/drew138/.dotfiles/installer/internal/infrastructure/provider:
    config:
      all: true
