---
- hosts: "{{ selected_hosts }}"
  tasks:
    - name: Include roles
      include_role:
        name: "{{ role }}"
      loop: "{{ selected_roles }}"
      loop_control:
        loop_var: role
  environment:
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY: "YES"
