---
- hosts: "{{ selected_hosts }}"
  tasks:
    - name: Include roles
      include_role:
        name: "{{ item }}"
      loop: "{{ selected_roles }}"
    # - name: reboot machine
    #   ansible.builtin.reboot:
    #     msg: "rebooting machine"
