---
- hosts: "{{ selected_hosts }}"
  vars_files:
    - ~/extra_vars.yml
  tasks:
    - name: Include roles
      include_role:
        name: "{{ role }}"
      loop: "{{ selected_roles }}"
      loop_control:
        loop_var: role
