---
- name: create /usr/local/include
  become: true
  file:
    path: /usr/local/include
    state: directory

- name: create /usr/local/include/bits
  become: true
  file:
    path: /usr/local/include/bits
    state: directory

- name: copy stdc++.h to /usr/local/include/bits
  become: true
  copy:
    src: /Users/asalazargale/.dotfiles/roles/cpp/files/stdc++.h
    dest: /usr/local/include/bits/stdc++.h
