---
- name: install go binaries
  become_user: "{{ ansible_env.USER }}"
  shell: /usr/local/go/bin/go install {{ item }}
  loop:
    - github.com/charmbracelet/gum@latest
    - github.com/go-delve/delve/cmd/dlv@latest
    - github.com/vektra/mockery/v2@latest
