---
driver:
  name: docker
platforms:
  - name: ubuntu
    image: "nmusatti/ubuntu2204-pys-systemd:latest"
    volumes:
      - /run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
verifier:
  name: testinfra
