- name: change splash screen engine to none
  become_user: "{{ host_user }}"
  shell: >
    kwriteconfig5 --file "{{ user_home }}/.config/ksplashrc" \
      --group KSplash \
      --key Engine none

- name: change splash screen to theme to none
  become_user: "{{ host_user }}"
  shell: >
    kwriteconfig5 --file "{{ user_home }}/.config/ksplashrc" \
      --group KSplash \
      --key Theme none
