---
- name: "see if dock item {{ dock_item_add.name | default(dock_item_add) }} exists"
  command: "dockutil --find '{{ dock_item_add.name }}'"
  register: dockitem_exists
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  changed_when: false

- name: get current dock section from output
  set_fact:
    current_section: "{{ dockitem_exists.stdout | regex_replace('^.*was found in (.*) at slot.*$', '\\1') }}"
  when: dockitem_exists.rc == 0

- name: ensure dock item {{ dock_item_add.name | default(dock_item_add) }} exists
  command: |
    dockutil --add '{{ dock_item_add.path }}' --label '{{ dock_item_add.name }}'
    {% if not ansible_loop.last %}--no-restart{% endif %}
  when: dockitem_exists.rc > 0 or
    dockitem_exists.rc == 0 and current_section == 'recent-apps'
  changed_when: false

- name: pause for 7 seconds between dock changes
  pause:
    seconds: 7
  when:
    - dockitem_exists.rc > 0 or
      dockitem_exists.rc == 0 and current_section == 'recent-apps'
    - ansible_loop.last
