---
- name: change dock preferences
  shell: "{{ item }}"
  args:
    executable: /bin/bash
  changed_when: false
  loop:
    - defaults write com.apple.dock autohide 1
    - defaults write com.apple.dock launchanim 0
    - defaults write com.apple.dock tilesize 36

- name: install dockutil
  become: true
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - dockutil
    state: latest

- name: clean up dock
  include_tasks: remove.yml
  loop: "{{ dockitems_remove }}"
  loop_control:
    extended: true
    extended_allitems: false

- name: Ensure required dock items exist.
  include_tasks: add.yml
  loop: "{{ dockitems_persist }}"
  loop_control:
    extended: true
    extended_allitems: false

- name: Ensure dock items are in correct position.
  include_tasks: position.yml
  when:
    - item.pos is defined
    - item.pos > 0
  loop: "{{ dockitems_persist }}"
  loop_control:
    extended: true
    extended_allitems: false
