---
- name: change dock preferences
  shell: >
    defaults write com.apple.dock autohide 1
    defaults write com.apple.dock launchanim 0
    defaults write com.apple.dock tilesize 36
  args:
    executable: /bin/bash
  changed_when: false

- name: install dockutil
  become: true
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - dockutil
    state: latest

# https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/dock/defaults/main.yml
# https://www.dummies.com/article/technology/computers/operating-systems/macos/big-sur/the-dock-in-macos-big-sur-275639/
# https://github.com/kcrawford/dockutil
