---
- name: change dock preferences
  shell: "{{ item }}"
  args:
    executable: /bin/bash
  changed_when: false
  loop:
    - defaults write com.apple.dock autohide 1
    - defaults write com.apple.dock launchanim 0
    - defaults write com.apple.dock tilesize 36
