---
galaxy_info:
  author: drew138
  description: sets up gpg configs
  license: MIT
  min_ansible_version: 2.16.1
  role_name: gpg
  namespace: drew138
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
dependencies:
  - role: homebrew
