---
- name: install utils (linux)
  package:
    name:
      - htop
      - ripgrep
      - python3-virtualenv
      - gcc
      - g++
      - protobuf-compiler
      - libstdc++-12-dev
  when: is_debian_distro

- name: install utils (macos)
  homebrew:
    name:
      - htop
      - ripgrep
      - virtualenv
      - protobuf
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists
