---
- name: install utils (linux)
  package:
    name:
      - htop
      - ripgrep
      - python3-virtualenv
      - gcc
      - g++
      - protobuf-compiler
      - libstdc++-12-dev
      - git
  when: is_debian_distro

# - name: install utils (macos)
#   become: true
#   become_user: "{{ host_user }}"
#   homebrew:
#     name:
#       - htop
#       - ripgrep
#       - virtualenv
#       - protobuf
#       - git
#     state: present
#   register: result
#   until: result is successful
#   when: is_macos and homebrew_check.stat.exists

- name: create .gitconfig.workrc file
  copy:
    content: ""
    dest: "{{ user_home }}/.gitconfig.work"
    backup: true
    force: false
    mode: "u+rwx"
    owner: "{{ host_user }}"
