- name: Fetch Neovim Installer
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.deb
    dest: /tmp/nvim-linux64.deb
    mode: '0755'
    force: 'yes'
  tags:
    - nvim
  when: ansible_distribution == "Ubuntu"

- name: Install Neovim
  command: apt-get install /tmp/nvim-linux64.deb
  args:
    warn: false
  tags:
    - nvim
  when: ansible_distribution == "Ubuntu"

- name: Install pynvim
  command: pip install pynvim
  tags:
    - nvim
  when: ansible_distribution == "Ubuntu"
