- name: install common utils
  package:
    name:
      - htop
      - tmux
      - ripgrep
      - fd-find
      - python3-pip
      - python3-virtualenv
      - flatpak
      - zsh
      - xclip
      - protobuf-compiler
      - kde-full
      # find ~ -type f -mmin -1 # find recently changed files
  when: is_debian_based_distribution

- name: add flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  when: is_debian_based_distribution
