- name: Install Common Utils
  package:
    name: 
      - htop
      - tmux
      - ripgrep
      - fd-find
      # - fzf pending
      - python3-virtualenv
      - flatpak
      - zsh
      - xclip

- name: Add flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

