- name: Download Installer
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    dest: /tmp/nvm_installer.sh
    mode: '0755'
    force: 'yes'
  tags:
    - nvm
  when: os_name == "ubuntu"

- name: Install Nvm
  become_user: "{{ ansible_env.SUDO_USER }}"
  script: '/tmp/nvm_installer.sh'
  tags:
    - nvm
  when: os_name == "ubuntu"
