---
- name: ensure .ssh directory exists
  become: true
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0700

- name: save decrypted variable to id_ed25519
  copy:
    content: "{{ ssh_github_private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    owner: "{{ ansible_env.USER }}"
    mode: 0600

- name: capture gitHub rsa key
  shell: ssh-keyscan -t rsa github.com
  register: github_rsa_key
  changed_when: false

- name: add gitHub rsa key to known_hosts file
  lineinfile:
    path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    line: "{{ github_rsa_key.stdout_lines }}"
    create: true
  loop: "{{ github_rsa_key.stdout_lines }}"
