---
- name: ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: save decrypted variable to id_ed25519
  copy:
    content: "{{ ssh_github_private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    owner: "{{ ansible_env.USER }}"
    mode: "0600"

- name: scan github rsa key
  shell: ssh-keyscan -t rsa github.com >> "{{ ansible_env.HOME }}/.ssh/known_hosts"
  args:
    creates: "{{ ansible_env.HOME }}/.ssh/known_hosts"
