- include_tasks: tasks/desktop/appearance/kvantum/kvantum.yml
- include_tasks: tasks/desktop/appearance/layan/layan.yml
- include_tasks: tasks/desktop/appearance/global-theme/global-theme.yml
- include_tasks: tasks/desktop/appearance/application-style/application-style.yml
- include_tasks: tasks/desktop/appearance/launch-feedback/launch-feedback.yml
- include_tasks: tasks/desktop/appearance/splashscreen/splashscreen.yml
