---
- name: install flatpak
  apt:
    name:
      - flatpak
    state: present

- name: add flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: install flatpak packages
  become: true
  become_user: "{{ flatpak_host_user }}"
  flatpak:
    name: "{{ item }}"
    method: user
    state: present
  loop:
    - com.brave.Browser
    - com.slack.Slack
    - com.spotify.Client
    - com.discordapp.Discord
    - md.obsidian.Obsidian
    - com.getpostman.Postman
    - com.obsproject.Studio
    - com.bitwarden.desktop
    - com.dropbox.Client
