---
- name: create fonts directories if they don't exist
  file:
    path: "{{ nerdfonts_user_home }}/.local/share/fonts"
    state: directory

- name: create symlink for NerdFonts directory
  file:
    src: "{{ nerdfonts_user_home }}/.dotfiles/roles/nerdfonts/files"
    dest: "{{ nerdfonts_user_home }}/.local/share/fonts/NerdFonts"
    owner: "{{ nerdfonts_host_user }}"
    state: link
    force: true
