---
- name: install zsh
  become: true
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - zsh
    state: latest

- name: create .workrc.zsh file
  copy:
    content: "#!/bin/bash"
    dest: "{{ ansible_env.HOME }}/.workrc.zsh"
    force: false
    mode: "u+rwx"
    owner: "{{ ansible_env.USER }}"
  args:
    creates: "{{ ansible_env.HOME }}/.workrc.zsh"

- name: change default shell
  become: true
  shell: "chsh -s $(which zsh) {{ ansible_env.USER }}"
  changed_when: false

- name: create .zshrc symlink
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/roles/zsh/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    state: link
    force: true
