---
- name: include tasks based on the operating system
  include_tasks: "{{ item }}"
  with_fileglob:
    - "{{ ansible_env.HOME }}/.dotfiles/roles/zsh/tasks"
  when: "ansible_os_family | lower in item"
