---
- name: install dependencies (linux)
  apt:
    name:
      - xclip
      - cmake
      - make
      - gettext
      - python3-pip
      - python3.10-venv
    state: present
  when: is_debian_distro

- name: install dependencies (macos)
  become: true
  become_user: "{{ host_user }}"
  homebrew:
    name:
      - xclip
      - cmake
      - make
      - python
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists

- name: create dev directory
  file:
    path: "{{ user_home }}/dev/"
    state: directory
    owner: "{{ host_user }}"

- name: clone nvim repository
  become: true
  become_user: "{{ host_user }}"
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ user_home }}/dev/neovim"
    version: release-0.9
    depth: 1
    clone: true
    update: true

- name: clean previous neovim build
  become: true
  shell:
    cmd: |
      sudo make distclean
    chdir: "{{ user_home }}/dev/neovim"

- name: build and install nvim
  become: true
  shell:
    cmd: |
      sudo make distclean
      sudo make CMAKE_BUILD_TYPE=RelWithDebInfo
      sudo make install
    chdir: "{{ user_home }}/dev/neovim"

- name: install pynvim
  ansible.builtin.pip:
    name: pynvim

- name: install global npm packages required by neovim
  become_user: "{{ host_user }}"
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: true
  loop:
    - "tree-sitter-cli"

- name: create nvim symlink
  file:
    src: "{{ user_home }}/.dotfiles/.config/nvim"
    dest: "{{ user_home }}/.config/nvim"
    owner: "{{ host_user }}"
    state: link
    force: true
