format = """$username\
$hostname\
$directory\
$python\
$golang\
$nodejs\
$git_branch
$character\
"""

add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[username]
format = "[$user]($style)"

[hostname]
format = ":[$hostname]($style) "

[python]
symbol = " "
pyenv_version_name = true
detect_extensions = []

[golang]
# symbol = " "
# symbol =''
format = '[ $version](bold cyan) '
detect_extensions = []

[nodejs]
detect_extensions = []
symbol = " "
