---
- name: check if go is installed
  shell: go version
  register: go_exists
  ignore_errors: true
  failed_when: "'go version' in go_exists.stdout"

- name: get kernel version
  command: "uname"
  register: uname_result

- name: debug go version
  debug:
    var: go_exists.stdout

- name: download go installer
  when: go_exists is not failed
  get_url:
    url: https://get.golang.org/{{ uname_result.stdout }}/go_installer
    dest: /tmp/go_installer
    mode: 0755
    force: "yes"

- name: install go
  become_user: "{{ host_user }}"
  when: go_exists is not failed
  script: "/tmp/go_installer"
...
