---
- name: install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: latest

- name: download hashicorp armored GPG key
  get_url:
    url: "{{ kubernetes_key_url }}/Release.key"
    dest: "{{ kubernetes_keyring_path }}"

- name: de-armor hashicorp GPG key
  command: "gpg --dearmor < {{ kubernetes_keyring_path }}_armored > {{ kubernetes_keyring_path }}"
  no_log: true
  args:
    creates: "{{ kubernetes_keyring_path }}"

- name: add kubernetes repository
  become: true
  apt_repository:
    repo: "deb [signed-by={{ kubernetes_keyring_path }}] {{ kubernetes_key_url }}/ /"
    filename: /etc/apt/sources.list.d/kubernetes.list

- name: install kubectl
  become: true
  apt:
    update_cache: true
    name: kubectl
    state: latest
