---
- name: unzip the aws cli installer
  unarchive:
    src: "{{ aws_cli_zip_url }}"
    dest: /tmp
    remote_src: true
  changed_when: false

- name: install the aws cli
  become: true
  command:
    cmd: ./install --bin-dir /usr/local/bin --install-dir {{ aws_cli_install_dir }} --update
    chdir: /tmp/aws
  changed_when: false

- name: cleanup temporary installation files and zip
  become: true
  file:
    path: "{{ item }}"
    state: absent
  changed_when: false
  loop:
    - "/tmp/aws"
