---
- name: install curl
  become: true
  become_user: "{{ kitty_host_user }}"
  homebrew:
    name:
      - curl
    state: present

- name: install kitty
  become: true
  become_user: "{{ kitty_host_user }}"
  shell: >
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

- name: create symbolic links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ kitty_host_user }}"
    state: link
    force: true
  loop: "{{ kitty_config_files }}"
