---
- name: include tasks based on the operating system
  include_tasks: "{{ item }}"
  with_fileglob:
    - "{{ kitty_user_home }}/.dotfiles/roles/kitty/tasks"
  when: "ansible_os_family | lower in item"
