- name: install kitty
  become_user: "{{ ansible_env.SUDO_USER }}"
  ansible.builtin.shell: >
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    warn: false
  when: has_kitty_terminal

- name: post install setup
  become_user: "{{ ansible_env.SUDO_USER }}"
  command: "~/.dotfiles/scripts/kitty_post_install.sh"
  when: is_debian_based_distribution and kitty_terminal == "true"
