- name: check installation
  stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: ohmyzsh_file

- name: download ohmyzsh installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: "0755"
    force: "yes"
  when: not ohmyzsh_file.stat.exists

- name: install ohmyzsh
  become: true
  command: /tmp/ohmyzsh_install.sh
  when: not ohmyzsh_file.stat.exists

- name: download syntax highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ user_home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes

- name: download auto suggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ user_home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    clone: yes
    update: yes

- name: change default shell
  become: true
  shell: "sudo chsh $USER -s $(which zsh)"
  args:
    warn: false
