---
- name: install git
  become: true
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - git
    state: latest

- name: create dev directory
  become: true
  file:
    path: "{{ ansible_env.HOME }}/dev/"
    state: directory
    mode: 0755
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: download dotfiles repository
  become: true
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: "git@github.com:drew138/.dotfiles.git"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    clone: true
    update: true

- name: download repositories
  become: true
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: "git@github.com:drew138/{{ item }}.git"
    dest: "{{ ansible_env.HOME }}/dev/{{ item }}"
    clone: true
    update: true
  with_items: "{{ repository_names }}"
