# ---
# - name: install utils (linux)
#   apt:
#     name:
#       - htop
#       - ripgrep
#       - python3-virtualenv
#       - gcc
#       - g++
#       - protobuf-compiler
#       - libstdc++-12-dev
#       - git
#       - jq
#     state: latest
#
# - name: install utils (macos)
#   become: true
#   become_user: "{{ host_user }}"
#   homebrew:
#     name:
#       - htop
#       - ripgrep
#       - virtualenv
#       - protobuf
#       - git
#       - python
#       - jq
#     state: latest
#
# - name: install pre-commit
#   pip:
#     name: pre-commit
#     state: latest
