---
- name: install dependencies
  package:
    name:
      - xclip
    state: present
  when: is_debian_distro

- name: install tmux
  package:
    name:
      - tmux
      - xclip
    state: present
  when: is_debian_distro

- name: install dependencies
  homebrew:
    name:
      - xclip
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists

- name: install tmux
  homebrew:
    name:
      - tmux
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists

- name: tmux package manager
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ user_home }}/.tmux/plugins/tpm"
    depth: 1
    clone: true
    update: true

- name: Create .tmux.conf symlink
  file:
    src: "{{ user_home }}/.dotfiles/.tmux.conf"
    dest: "{{ user_home }}/.tmux.conf"
    state: link
    force: true
...
