---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Debug variable
      debug:
        msg: "{{ lookup('env', 'HOME')}} of{{ lookup('env', 'USER')}} my_variable is {{ ansible_env }}"

    - name: check if defaults exists
      stat:
        path: "./roles/{{ ansible_env.MOLECULE_ROLE }}/defaults/main.yml"
      register: defaults_stat

    - name: include defaults
      include_vars: "./roles/{{ ansible_env.MOLECULE_ROLE }}/defaults/main.yml"
      when: defaults_stat.stat.exists

    - name: check if vars exists
      stat:
        path: "./roles/{{ ansible_env.MOLECULE_ROLE }}/vars/main.yml"
      register: vars_stat

    - name: include vars
      include_vars: "./roles/{{ ansible_env.MOLECULE_ROLE }}/vars/main.yml"
      when: vars_stat.stat.exists

    - name: check if tasks exists
      stat:
        path: "./roles/{{ ansible_env.MOLECULE_ROLE }}/tasks/main.yml"
      register: tasks_stat

    - name: include tasks
      include_tasks: "./roles/{{ ansible_env.MOLECULE_ROLE }}/tasks/main.yml"
      when: tasks_stat.stat.exists

    - name: check if handlers exists
      stat:
        path: "./roles/{{ ansible_env.MOLECULE_ROLE }}/handlers/main.yml"
      register: handlers_stat

    - name: include handlers
      include_tasks: "./roles/{{ ansible_env.MOLECULE_ROLE }}/handlers/main.yml"
      when: handlers_stat.stat.exists
