---
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: docker
platforms:
- name: ubuntu
  image: "geerlingguy/docker-ubuntu2204-ansible:latest"
  command: ""
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:rw
  cgroupns_mode: host
  privileged: true
  pre_build_image: true
  Dockerfile: |
    FROM geerlingguy/docker-ubuntu2204-ansible:latest
    RUN useradd -ms /bin/bash drew
    RUN echo "drew ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    USER drew

- name: macos
  image: "sickcodes/docker-osx:latest"
  privileged: true
  pre_build_image: true
  Dockerfile: |
    FROM sickcodes/docker-osx:latest
    RUN useradd -ms /bin/bash drew
    RUN echo "drew ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    USER drew
provisioner:
  name: ansible
verifier:
  name: ansible
