---
- name: clone fzf repo
  become: true
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ ansible_env.HOME }}/.fzf"
    depth: 1
    clone: true
    update: true

- name: install fzf
  become: true
  become_user: "{{ ansible_env.USER }}"
  command: "{{ ansible_env.HOME }}/.fzf/install"
  changed_when: false

- name: revert path changes
  shell: |
    git checkout .
  args:
    chdir: "{{ ansible_env.HOME }}/.dotfiles"
  changed_when: false
