---
- name: ensure homebrew is installed
  become: true
  changed_when: false
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  args:
    executable: /bin/bash
