---
# DO NOT CHANGE ELEVATION OF PERMISSIONS

# - name: Check if Homebrew is installed
#   become: true
#   command: brew --version
#   register: brew_check
#   ignore_errors: yes

- name: ensure homebrew is installed
  become_user: "{{ ansible_env.USER }}"
  changed_when: false
  shell: 'echo {{ ansible_become_password }} | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  # environment:
  #   NONINTERACTIVE: "1"
  args:
    executable: /bin/bash
