---
- name: fetch latest release data
  uri:
    url: "https://api.github.com/repos/Homebrew/brew/releases/latest"
    method: GET
    return_content: true
    headers:
      Accept: "application/vnd.github.v3+json"
      Authorization: "token {{ lookup('env','GHUB_ACCESS_TOKEN') }}"
  register: release_data

- name: extract url for Homebrew.pkg
  set_fact:
    pkg_url: "{{ release_data.json['assets'] | selectattr('name', 'search', '.pkg') | map(attribute='browser_download_url') | first }}"

- name: download Homebrew.pkg
  ansible.builtin.get_url:
    url: "{{ pkg_url }}"
    dest: /tmp/Homebrew.pkg
  changed_when: false

- name: install Homebrew.pkg
  become: true
  command:
    cmd: "installer -pkg /tmp/Homebrew.pkg -target /"

- name: Clean up .pkg file
  file:
    path: /tmp/Homebrew.pkg
    state: absent
  changed_when: false
