---
- name: ensure homebrew is installed
  become: true
  become_user: "{{ ansible_env.USER }}"
  command: "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
  args:
    creates: /usr/local/bin/brew
