---
- name: ensure homebrew is installed
  become_user: "{{ ansible_env.USER }}"
  changed_when: false
  shell: "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
  args:
    executable: /bin/bash
