- name: Create .gitconfig symlink
  file:
    src: "{{ user_home }}/.dotfiles/.gitconfig"
    dest: "{{ user_home }}/.gitconfig"
    state: link
    force: yes

- name: Create .zshrc symlink
  file:
    src: "{{ user_home }}/.dotfiles/.zshrc"
    dest: "{{ user_home }}/.zshrc"
    state: link
    force: yes

- name: Create .tmux.conf symlink
  file:
    src: "{{ user_home }}/.dotfiles/.tmux.conf"
    dest: "{{ user_home }}/.tmux.conf"
    state: link
    force: yes

- name: Create kitty.conf symlink
  file:
    src: "{{ user_home }}/.dotfiles/.config/kitty/kitty.conf"
    dest: "{{ user_home }}/.config/kitty/kitty.conf"
    state: link
    force: yes

- name: Create nightfox_kitty.conf symlink
  file:
    src: "{{ user_home }}/.dotfiles/.config/kitty/nightfox_kitty.conf"
    dest: "{{ user_home }}/.config/kitty/nightfox_kitty.conf"
    state: link
    force: yes

- name: Create nvim symlink
  file:
    src: "{{ user_home }}/.dotfiles/.config/nvim"
    dest: "{{ user_home }}/.config/nvim"
    state: link
    force: yes
