---
- name: create fonts directories if they don't exist (linux)
  file:
    path: "{{ user_home }}/.local/share/fonts"
    state: directory
  when: is_debian_distro

- name: create symlink for NerdFonts directory (linux)
  file:
    src: "{{ user_home }}/.dotfiles/assets/fonts/NerdFonts"
    dest: "{{ user_home }}/.local/share/fonts"
    owner: "{{ host_user }}"
    state: link
    force: true
  when: is_debian_distro

- name: create Fonts directory if it doesn't exist (macos)
  become: true
  file:
    path: "{{ user_home }}/Library/Fonts"
    state: directory
  when: is_macos

- name: create symbolic links for NerdFonts (macos)
  with_fileglob: "{{ user_home }}/.dotfiles/assets/fonts/NerdFonts/*"
  vars:
    destination_file: "{{ user_home }}/Library/Fonts/{{ item | regex_replace('.*/', '') }}"
  file:
    src: "{{ item }}"
    dest: "{{ destination_file }}"
    owner: "{{ host_user }}"
    force: true
  when: is_macos
