---
- name: install nodejs prerequisites (linux)
  become_user: "{{ host_user }}"
  apt:
    name:
      - apt-transport-https
      - gcc
      - g++
      - make
    state: present
  when: is_debian_distro

- name: install nvm
  become: true
  become_user: "{{ host_user }}"
  ansible.builtin.shell: >
    curl -o- {{ nvm_script_url }} | bash
  args:
    warn: false
    creates: "{{ user_home }}/.nvm/nvm.sh"

- name: install node
  become: false
  shell: >
    . {{ user_home }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ user_home }}"
    creates: "{{ user_home }}/.nvm/versions/{{ item }}"
  loop:
    - "{{ node_version }}"

- name: create node symlink to /usr/bin
  file:
    src: "{{ user_home }}/.nvm/versions/node/v19.9.0/bin/node"
    dest: "/usr/bin/node"
    owner: "{{ host_user }}"
    state: link
    force: true
  when: is_debian_distro

- name: create npm symlink to /usr/bin
  file:
    # change version below to install higher versions
    src: "{{ user_home }}/.nvm/versions/node/v19.9.0/bin/npm"
    dest: "/usr/bin/npm"
    owner: "{{ host_user }}"
    state: link
    force: true
  when: is_debian_distro
