---
- name: installs homebrew cask packages
  become: true
  become_user: "{{ casks_host_user }}"
  homebrew_cask:
    name:
      - brave-browser
      - slack
      - spotify
      - discord
      - obsidian
      - postman
      - obs
      - bitwarden
      - notion
      - whatsapp
      - dropbox
    state: present
