---
- name: install homebrew casks
  include_tasks: install_cask.yml
  loop_control:
    extended: true
    extended_allitems: false
  loop:
    - brave-browser
    - dbeaver-community
    - slack
    - spotify
    - discord
    - obsidian
    - postman
    - obs
    - bitwarden
    - notion
    - notion-calendar
    - logitech-g-hub
    - whatsapp
    - dropbox
