---
- name: installs homebrew cask packages
  homebrew_cask:
    name:
      - brave-browser
      - dbeaver-community
      - slack
      - spotify
      - discord
      - obsidian
      - postman
      - obs
      - bitwarden
      - notion
      - whatsapp
      - dropbox
    state: present
  become: true
  become_user: "{{ ansible_env.USER }}"
