---
- name: install terraform
  become: true
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - terraform
    state: latest

- name: install terraform autocomplete
  command: terraform -install-autocomplete
