---
- name: install required packages
  apt:
    name:
      - gnupg
      - software-properties-common
      - lsb-release
    state: latest

- name: download and add hashicorp GPG key
  apt_key:
    url: "{{ hashicorp_repo_url }}/gpg"
    keyring: "{{ hashicorp_keyring_path }}"

- name: add hashicorp repository
  apt_repository:
    repo: "deb [signed-by={{ hashicorp_keyring_path }}] {{ hashicorp_repo_url }} $(lsb_release -cs) main"
    filename: /etc/apt/sources.list.d/hashicorp.list

- name: update package cache and install terraform
  apt:
    update_cache: true
    name: terraform
    state: latest
