- name: install latte dock dependencies
  apt:
    name:
      - cmake
      - extra-cmake-modules
      - qtdeclarative5-dev
      - libqt5x11extras5-dev
      - libkf5iconthemes-dev
      - libkf5plasma-dev
      - libkf5windowsystem-dev
      - libkf5declarative-dev
      - libkf5xmlgui-dev
      - libkf5activities-dev
      - build-essential
      - libxcb-util-dev
      - libkf5wayland-dev
      - gettext
      - libkf5archive-dev
      - libkf5notifications-dev
      - libxcb-util0-dev
      - libsm-dev
      - libkf5crash-dev
      - libkf5newstuff-dev
      - libxcb-shape0-dev
      - libxcb-randr0-dev
      - libx11-dev
      - libx11-xcb-dev
      - kirigami2-dev
    state: present

- name: get latte dock repository
  git:
    repo: "https://github.com/KDE/latte-dock.git"
    dest: "/tmp/latte-dock"
    clone: yes
    update: yes

- name: install latte dock
  become: true
  shell: >
    sh /tmp/latte-dock/install.sh

- name: post install cleanup
  apt:
    name:
      - cmake
      - extra-cmake-modules
      - qtdeclarative5-dev
      - libqt5x11extras5-dev
      - libkf5iconthemes-dev
      - libkf5plasma-dev
      - libkf5windowsystem-dev
      - libkf5declarative-dev
      - libkf5xmlgui-dev
      - libkf5activities-dev
      - build-essential
      - libxcb-util-dev
      - libkf5wayland-dev
      - gettext
      - libkf5archive-dev
      - libkf5notifications-dev
      - libxcb-util0-dev
      - libsm-dev
      - libkf5crash-dev
      - libkf5newstuff-dev
      - libxcb-shape0-dev
      - libxcb-randr0-dev
      - libx11-dev
      - libx11-xcb-dev
      - kirigami2-dev
    state: absent
