- name: install latte dock dependencies
  apt:
    name:
      - latte-dock
    state: present

# - name: run latte dock
#   become_user: "{{ host_user }}"
#   environment:
#     XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
#   shell: |
#     latte-dock

- name: Create symbolic link
  file:
    src: "{{ user_home }}/.dotfiles/assets/latte/layout.layout.latte"
    dest: "{{ user_home }}/.config/latte/layout.layout.latte"
    state: link
    force: yes

- name: switch latte dock layout
  become_user: "{{ host_user }}"
  shell: >
    kwriteconfig5 --file "{{ user_home }}/.config/lattedockrc" \
      --group UniversalSettings \
      --key singleModeLayoutName layout
