---
- name: change keyboard repeat rates
  shell: "{{ item }}"
  args:
    executable: /bin/bash
  changed_when: false
  loop:
    - defaults write -g InitialKeyRepeat -int 15
    - defaults write -g KeyRepeat -int 2
