---
- name: install i3 (linux)
  apt:
    name:
      - i3
      - feh
      # - picom
      - dmenu
      - polybar
    state: present
  when: is_debian_distro

- name: create i3 directory if it does not exist (linux)
  file:
    path: "{{ user_home }}/.config/i3"
    state: directory
  when: is_debian_distro

- name: create i3 symlink (linux)
  file:
    src: "{{ user_home }}/.dotfiles/.config/i3/config"
    dest: "{{ user_home }}/.config/i3/config"
    owner: "{{ host_user }}"
    state: link
    force: true
  when: is_debian_distro

- name: install build packages for i3lock-color
  apt:
    name:
      - autoconf
      - gcc
      - make
      - pkg-config
      - libpam0g-dev
      - libcairo2-dev
      - libfontconfig1-dev
      - libxcb-composite0-dev
      - libev-dev
      - libx11-xcb-dev
      - libxcb-xkb-dev
      - libxcb-xinerama0-dev
      - libxcb-randr0-dev
      - libxcb-image0-dev
      - libxcb-util-dev
      - libxcb-xrm-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libjpeg-dev
    state: present
  when: is_debian_distro

- name: clone i3lock-color repository
  become: true
  become_user: "{{ host_user }}"
  git:
    repo: "https://github.com/Raymo111/i3lock-color.git"
    dest: "{{ user_home }}/i3lock-color"
    depth: 1
    clone: true
    update: true

- name: build and install i3lock-color
  become: true
  shell:
    cmd: "{{ user_home }}/i3lock-color/install-i3lock-color.sh"
    chdir: "{{ user_home }}/i3lock-color"
  args:
    warn: false


- name: install audio required packages
  apt:
    name:
      - pulseaudio-module-bluetooth
      - pulseaudio-equalizer
      - pulseaudio-module-jack
      - alsa-utils
      - playerctl
    state: present
  when: is_debian_distro

# - name: install build packages for xidlehook
#   apt:
#     name:
#       - libxcb
#       - libxss
#       - libpulseaudio
#       - libxcb-dev
#       - libxss-dev
#       - libpulseaudio-dev
#     state: present
#   when: is_debian_distro
#
# - name: clone xidlehook repository
#   become: true
#   become_user: "{{ host_user }}"
#   git:
#     repo: "https://gitlab.com/jD91mZM2/xidlehook"
#     dest: "{{ user_home }}/xidlehook"
#     depth: 1
#     clone: true
#     update: true
#
# - name: build and install xidlehook
#   become: true
#   become_user: "{{ host_user }}"
#   shell:
#     cmd: cargo build --release --bins
#     dest: "{{ user_home }}/xidlehook"
#   args:
#     warn: false
...
