---
- name: install git (linux)
  apt:
    name:
      - git
    state: present
  when: is_debian_distro

- name: install git (macos)
  homebrew:
    name:
      - git
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists

- name: create .gitconfig symlink
  file:
    src: "{{ user_home }}/.dotfiles/.gitconfig"
    dest: "{{ user_home }}/.gitconfig"
    state: link
    force: true

- name: create .gitconfig.work file
  copy:
    content: ""
    dest: "{{ user_home }}/.gitconfig.work"
    backup: true
    force: false
    mode: "u+rwx"
    owner: "{{ host_user }}"
