---
- name: install dependencies
  become: true
  apt:
    name:
      - xclip
      - tmux
    state: latest
  notify:
    - install tmux plugins

- name: tmux package manager
  become: true
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    depth: 1
    clone: true
    update: true

- name: create .tmux.conf symlink
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/roles/tmux/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ ansible_env.USER }}"
    state: link
    force: true
