---
- name: install nodejs prerequisites
  become_user: "{{ ansible_env.USER }}"
  apt:
    name:
      - apt-transport-https
      - gcc
      - g++
      - make
    state: latest

- name: install node
  shell: nvm install --lts
  changed_when: false
