---
# - name: install nodejs prerequisites
#   become: true
#   apt:
#     name:
#       - apt-transport-https
#       - gcc
#       - g++
#       - make
#     state: latest

- name: install node
  become: true
  become_user: "{{ ansible_env.USER }}"
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts"
  changed_when: false
  args:
    executable: /bin/bash
