---
- name: install nodejs prerequisites
  become: true
  apt:
    name:
      - apt-transport-https
      - gcc
      - g++
      - make
    state: latest

- name: install node
  shell: "{{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts"
  changed_when: false
