---
- name: install nodejs prerequisites
  become: true
  become_user: "{{ ansible_env.USER }}"
  apt:
    name:
      - apt-transport-https
      - gcc
      - g++
      - make
    state: latest

- name: Find files and directories
  find:
    paths: /your/directory/path
  register: files_and_directories_found

- name: Print files and directories
  debug:
    msg: "{{ item.path }}"
  loop: "{{ files_and_directories_found.files }}"
  when: item.isdir == False

- name: install node
  shell: source "{{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts"
  changed_when: false
