---
- name: installing homebrew cask packages (macos)
  become: true
  become_user: "{{ host_user }}"
  homebrew_cask:
    name:
      - brave-browser
      - slack
      - spotify
      - discord
      - obsidian
      - postman
      - obs
      - bitwarden
      - notion
      - whatsapp
      - dropbox
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists and has_user_repositories
