---
- name: clone fzf repo
  git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ user_home }}/.fzf"
    depth: 1
    clone: true
    update: true

- name: install fzf
  become_user: "{{ host_user }}"
  command: "{{ user_home }}/.fzf/install"
...
