# - name: Set profile picture using kwriteconfig5
#   # become: yes
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   shell: >
#     kwriteconfig5 --file kdeglobals --group User --key Picture ~/.dotfiles/desktop/profile.png

- name: change wallpaper
  shell: >
    plasma-apply-wallpaperimage {{ user_home }}/.dotfiles/assets/images/wallpaper.jpg

# - name: install kvantum dependencies
#   apt:
#     name:
#       - g++
#       - libx11-dev
#       - libxext-dev
#       - qtbase5-dev
#       - libqt5svg5-dev
#       - libqt5x11extras5-dev
#       - qttools5-dev-tools
#     state: present
#
# - name: get kvantum repository
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   git:
#     repo: "https://github.com/tsujan/Kvantum.git"
#     dest: "/tmp/Kvantum"
#     clone: yes
#     update: yes
#
# - name: get layan repository
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   git:
#     repo: "https://github.com/vinceliuice/Layan-kde.git"
#     dest: "/tmp/Layan-kde"
#     clone: yes
#     update: yes
#
# - name: get layan gtk theme repository
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   git:
#     repo: "https://github.com/vinceliuice/Layan-gtk-theme.git"
#     dest: "/tmp/Layan-gtk-theme"
#     clone: yes
#     update: yes
#
# - name: build and install kvantum theme
#   ansible.builtin.command:
#     cmd:
#       - qmake && make
#       - make install
#     args:
#       chdir: /tmp/Kvantum/Kvantum
#
# - name: install layan kvantum theme and layan kde theme
#   ansible.builtin.command:
#     cmd:
#       - /tmp/Layan-kde/install.sh
#       - /tmp/Layan-gtk-theme/install.sh
#
# - name: change widget style to kvantum dark
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   shell: >
#     kwriteconfig5 --file kdeglobals --group KDE \
#     --key widgetStyle kvantum-dark
#
# # TODO revisar si este si aplica
# # - name: change kvantum theme to layan
# #   become_user: "{{ ansible_env.SUDO_USER }}"
# #   shell: >
# #     kwriteconfig5 --file plasmarc --group Theme \
# #     --key name Layan
#
# - name: change kvantum theme to layan
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   shell: >
#     kwriteconfig5 --file ~/.config/Kvantum/kvantum.kvconfig \
#       --group General \
#       --key theme LayanSolidDark
#
# - name: change splash screen to none
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   shell: >
#     kwriteconfig5 --file kplashrc \
#       --group KSplash \
#       --key Engine none
#       --key Theme none
