# - name: Set profile picture using kwriteconfig5
#   # become: yes
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   shell: >
#     kwriteconfig5 --file kdeglobals --group User --key Picture ~/.dotfiles/desktop/profile.png

- name: Set keybind using kwriteconfig5
  # become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"
  shell: >
    kwriteconfig5 --file kglobalshortcutsrc --group Spectacle \
    --key RectangularRegion "<Ctrl+Meta+S>"
  # args:
  #   executable: /bin/bash
  # vars:
  #   username: <username>

# - name: Set keybind using kwriteconfig5
#   become: yes
#   become_user: <username>
#   shell: >
#     kwriteconfig5 --file kglobalshortcutsrc --group Spectacle \
#     --key GlobalShortcut "<Print>"
#   args:
#     executable: /bin/bash
#   vars:
#     username: <username>
