- name: get applet latte spacer repository
  git:
    repo: "https://github.com/psifidotos/applet-latte-spacer.git"
    dest: "/tmp/applet-latte-spacer"
    clone: yes
    update: yes

- name: install latte spacer
  become: true
  become_user: "{{ host_user }}"
  command: plasmapkg2 -i /tmp/applet-latte-spacer
  args:
    creates: "{{ user_home }}/.local/share/plasma/plasmoids/org.kde.latte.spacer"
