---
- name: install pyenv prerequisites
  become_user: "{{ ansible_env.USER }}"
  apt:
    name:
      - curl
      - git-core
      - gcc
      - make
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - tk-dev
      - liblzma-dev
    state: present

- name: clone pyenv repository
  become: true
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ ansible_env.HOME }}/.pyenv"
    depth: 1
    clone: true
    update: true
