- name: updating homebrew
  homebrew:
    update_homebrew: true
  when: is_macos and homebrew_check.stat.exists

- name: upgrading homebrew packages
  homebrew:
    upgrade_all: true
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists

- name: installing homebrew cask packages
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists and has_user_repositories

- name: installing homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists
