- name: updating homebrew
  homebrew:
    update_homebrew: true
  when: ansible_distribution == "MacOSX" and homebrew_check.stat.exists

- name: upgrading homebrew packages
  homebrew:
    upgrade_all: true
  register: result
  until: result is successful
  when: ansible_distribution == "MacOSX" and homebrew_check.stat.exists

- name: installing homebrew cask packages
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
  register: result
  until: result is successful
  when: ansible_distribution == "MacOSX" and homebrew_check.stat.exists and and extra_software == "true"

- name: installing homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: result
  until: result is successful
  when: ansible_distribution == "MacOSX" and homebrew_check.stat.exists
