- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False
  vars:
    user_repositories: "{{ lookup('env', 'USER_REPOSITORIES') }}"
    os_name: "{{ ansible_facts['distribution'] }}"

#ehttps://medium.com/espinola-designs/manage-your-dotfiles-with-ansible-6dbedd5532bb


  tasks:
    # repositories
    # - include: tasks/repositories/self.yml
    - include: tasks/repositories/tpm.yml
    - include: tasks/repositories/fzf.yml
    # utils
    - include: tasks/utils/common.yml
    - include: tasks/utils/docker.yml
    # - include: tasks/utils/kitty.yml
    # - include: tasks/utils/nvim.yml
    # - include: tasks/utils/ohmyzsh.yml
    # - include: tasks/utils/nvm.yml
    # - include: tasks/utils/fzf.yml

    # programming languages
    # - include: tasks/programming_languages/go.yml
    # - include: tasks/programming_languages/node.yml
    # - include: tasks/programming_languages/rust.yml
    # software
    # - include: tasks/software/discord.yml
    # - include: tasks/software/firefox.yml
    # - include: tasks/software/obsidian.yml
    # - include: tasks/software/postman.yml
    # - include: tasks/software/slack.yml
    # - include: tasks/software/spotify.yml
    # handlers:
    # - include: handlers/docker.yml
