- hosts: localhost
  become: true
  vars:
    - user_repositories: "{{ USER_REPOSITORIES }}"
    - kitty_terminal: "{{ KITTY_TERMINAL }}"
    - local_user: "{{ ansible_env.SUDO_USER }}"
    - include: tasks/macos/brew_packages.yml
    - include: tasks/macos/cask_packages.yml
    - allow_world_readable_tmpfiles: true

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: ensuring homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check
      when: ansible_distribution == "MacOSX"

  tasks:
    # ubuntu
    - include: tasks/ubuntu/utils.yml
    - include: tasks/ubuntu/nvim.yml
    - include: tasks/ubuntu/docker.yml
    - include: tasks/ubuntu/software.yml

    # macos
    - include: tasks/macos/install.yml

    # common
    # repositories
    - include: tasks/common/repositories/self.yml
    - include: tasks/common/repositories/tpm.yml
    - include: tasks/common/repositories/fzf.yml # become
    # programming languages
    - include: tasks/common/programming_languages/go.yml # become
    - include: tasks/common/programming_languages/node.yml
    - include: tasks/common/programming_languages/rust.yml # become
    # software
    - include: tasks/common/software/kitty.yml # become
    - include: tasks/common/software/nvm.yml
    - include: tasks/common/software/ohmyzsh.yml # become


  handlers:
    - include: handlers/docker.yml
