---
- name: install docker, docker-compose and colima
  become: true
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - docker
      - colima
      - docker-compose
    state: present
