---
- name: installs docker
  become_user: "{{ ansible_env.USER }}"
  homebrew_cask:
    name:
      - docker
    state: present
  ignore_errors: true

- name: install docker-compose and colima
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - colima
      - docker-compose
    state: latest
