---
- name: install dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest

- name: download docker armored GPG key
  become: true
  get_url:
    url: "{{ docker_repo_url }}/gpg"
    dest: "{{ docker_keyring_path }}"

- name: get system architecture
  command: dpkg --print-architecture
  register: system_architecture

- name: get os version codename
  shell: ". /etc/os-release && echo $VERSION_CODENAME"
  register: os_version_codename

- name: add docker repository
  become: true
  apt_repository:
    repo: "deb [arch={{ system_architecture.stdout }} signed-by={{ docker_keyring_path }}] {{ docker_repo_url }} {{ os_version_codename.stdout }} stable"
    state: present

- name: install docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: make sure docker is active
  service:
    name: docker
    state: started
    enabled: true

- name: add remote user to "docker" group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: "docker"
    append: true

- name: install docker-compose
  get_url:
    url: "{{ docker_compose_Linux_x86_64 }}"
    dest: /usr/local/bin/docker-compose
    mode: "+x"
  notify:
    - restart docker
