---
- name: change appearance to darkmode
  shell: osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'
  args:
    executable: /bin/bash
  changed_when: false
