- name: get applet window title repository
  git:
    repo: "https://github.com/psifidotos/applet-window-title.git"
    dest: "/tmp/applet-window-title"
    clone: yes
    update: yes

- name: install window title
  become: true
  become_user: "{{ host_user }}"
  command: plasmapkg2 -i /tmp/applet-window-title
  args:
    creates: "{{ user_home }}/.local/share/plasma/plasmoids/org.kde.windowtitle"
