- name: clone fzf repo
  become_user: "{{ ansible_env.SUDO_USER }}"
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest:  '~/.fzf'
    depth: 1
    clone: yes
    update: yes
  tags:
    - Fzf

- name: install fzf
  become_user: local_user
  command: ~/.fzf/install
  tags:
    - Fzf
