format = """$username\
$hostname\
$directory\
$character\
$python\
$golang\
$git_branch
"""

add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[username]
format = "[$user]($style)"

[hostname]
format = ":[$hostname]($style) "

[python]
pyenv_version_name = true

[golang]
symbol = 'Go '
