---
- name: install dependencies
  apt:
    name:
      - xclip
      - cmake
      - make
      - gettext
      - python3-pip
      - python3.10-venv
    state: present

- name: clone nvim repository
  become: true
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ ansible_env.HOME }}/dev/neovim"
    version: "{{ nvim_release_branch }}"
    depth: 1
    clone: true
    update: true

- name: clean previous neovim build
  become: true
  shell:
    cmd: |
      sudo make distclean
    chdir: "{{ ansible_env.HOME }}/dev/neovim"

- name: build and install nvim
  become: true
  shell:
    cmd: |
      sudo make distclean
      sudo make CMAKE_BUILD_TYPE=RelWithDebInfo
      sudo make install
    chdir: "{{ ansible_env.HOME }}/dev/neovim"

- name: install pynvim
  pip:
    name: pynvim

- name: install global npm packages required by neovim
  become_user: "{{ ansible_env.USER }}"
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: true
  loop:
    - "tree-sitter-cli"

- name: create nvim symlink
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/roles/nvim/files"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    owner: "{{ ansible_env.USER }}"
    state: link
    force: true
