---
- name: install fd-find
  become: true
  apt:
    name:
      - fd-find
    state: latest

- name: create bin directory if it doesn't exist
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: create symlink for fdfind
  file:
    src: "{{ lookup('pipe', 'which fdfind') }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/fd"
    owner: "{{ ansible_env.USER }}"
    state: link
    force: true
