---
# name: deploy laravel
# on:
#   push:
#     branches: [main]
#
# jobs:
#   example_matrix:
#     strategy:
#       matrix:
#         version: [10, 12, 14]
#         os: [macos-latest, windows-latest]
#     runs-on: ${{ matrix.os }}

name: test ansible roles

on: [push]

jobs:
  # check-roles:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: list ansible roles
  #
  #       run: command ls | cat >> $GITHUB_OUTPUT
  #       with:
  #         path: ./ansible/roles/
  #
  # test:
  #   needs:
  #     - lint
  #   runs-on: ubuntu-20.04
  #   strategy:
  #     matrix:
  #       image:
  #         - alpine
  #         - amazonlinux
  #         - debian
  #         - centos
  #         - fedora
  #         - opensuse
  #         - ubuntu
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #       with:
  #         path: "${{ github.repository }}"
  #     - name: molecule
  #       uses: robertdebock/molecule-action@6.0.0
  #       with:
  #         image: "${{ matrix.image }}"
  #         options: parallel
  #         scenario: my_specific_scenario

  vagrant-up:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
