---
- name: install fd-find (linux)
  apt:
    name:
      - fd-find
    state: present
  when: is_debian_distro

- name: create bin directory if it doesn't exist (linux)
  file:
    path: "{{ user_home }}/.local/bin"
    state: directory
  when: is_debian_distro

- name: create symlink for fdfind (linux)
  file:
    src: "{{ lookup('pipe', 'which fdfind') }}"
    dest: "{{ user_home }}/.local/bin/fd"
    owner: "{{ host_user }}"
    state: link
    force: true
  when: is_debian_distro

- name: install fd (macos)
  become: true
  become_user: "{{ host_user }}"
  homebrew:
    name:
      - fd
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists
