---
- name: install fd-find
  apt:
    name:
      - fd-find
    state: present
  when: is_debian_distro

- name: Create parent directories if they don't exist
  file:
    path: "{{ user_home }}/.local/bin"
    state: directory
  when: is_debian_distro

- name: create symlink for fdfind
  file:
    src: "{{ lookup('pipe', 'which fdfind') }}"
    dest: "{{ user_home }}/.local/bin/fd"
    state: link
    force: true
  when: is_debian_distro

- name: install fd
  homebrew:
    name:
      - fd
    state: present
  register: result
  until: result is successful
  when: is_macos and homebrew_check.stat.exists
...
