---
- name: install various clis
  become_user: "{{ ansible_env.USER }}"
  homebrew:
    name:
      - htop
      - ripgrep
      - virtualenv
      - protobuf
      - git
      - python
      - jq
      - bat
      - zoxide
      - curl
      - wget
      - gnu-tar

      # required by python for scikit
      # learn god knows why
      - llvm
      - libomp
    state: latest

- name: install pre-commit
  pip:
    name: pre-commit
    state: latest
