---
- name: install various clis
  become: true
  apt:
    name:
      - htop
      - ripgrep
      - python3-virtualenv
      - gcc
      - g++
      - protobuf-compiler
      - libstdc++-12-dev
      - git
      - jq
      - bat
      - zoxide
      - curl
      - wget
    state: latest

- name: ensure virtual environment is created
  command: python3 -m venv "{{ ansible_env.HOME }}/.clitools"
  args:
    creates: "{{ ansible_env.HOME }}/.clitools/bin/activate"

- name: install pre-commit and poetry in virtual environment
  pip:
    name:
      - pre-commit
      - poetry
    state: latest
    virtualenv: "{{ ansible_env.HOME }}/.clitools"
