---
- name: install various clis
  become: true
  apt:
    name:
      - htop
      - ripgrep
      - python3-virtualenv
      - gcc
      - g++
      - protobuf-compiler
      - libstdc++-12-dev
      - git
      - jq
      - bat
      - zoxide
      - curl
      - wget
    state: latest

- name: install pre-commit
  pip:
    name: pre-commit
    state: latest
